name: Docker Image CI

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine version
        id: get_version
        run: |
          DATE_TAG=$(date +'%Y%m%d%H%M%S')
          SHORT_SHA=${GITHUB_SHA::7}
          echo "VERSION=${DATE_TAG}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build the MySQL Docker image
        run: docker build ./mysql --file ./mysql/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/mysql-image:${{ env.VERSION }}

      - name: Push the MySQL Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mysql-image:${{ env.VERSION }}

      - name: Build the WordPress Docker image
        run: docker build ./Wordpress --file ./Wordpress/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/wordpres-image:${{ env.VERSION }}

      - name: Push the WordPress Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wordpres-image:${{ env.VERSION }}
